FROM golang:1.14-alpine as builder

WORKDIR /go/src/cluster-autoscaler

COPY . .

RUN GOOS=linux GOARCH=arm64 go build -v -o cluster-autoscaler

FROM arm64v8/alpine:latest

COPY --from=builder /go/src/cluster-autoscaler/cluster-autoscaler /usr/bin/cluster-autoscaler

ENTRYPOINT ["/usr/bin/cluster-autoscaler"]
